version: '3'

services:   

  mysql:
    command: mysqld --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.11
    environment:
      MYSQL_ROOT_PASSWORD: 'welcome1'
      MYSQL_DATABASE: 'empidb'
    volumes:
      - /tmp/db/data/mysql:/tmp/lib/mysql
    ports:
      - "3306:3306"
      
#  webapp:
#    image: springapp1
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    environment:
#      JVM_ARGUMENTS: "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"  
  
volumes:
  db_data: