# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.108.8.192:5000/liuhw99/springapp1
  tag: 0.0.10
  pullPolicy: IfNotPresent
service:
  name: springapp1
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

mysql:
  user: root
  password: welcome1
user:
  signature: Huawei Dev2
  
mysql:
  mysqlRootPassword: welcome1
  mysqlDatabase: empidb
  persistence:
    size: 200Mi  