kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "fullname" . }}
data:
  user.signature: {{ .Values.user.signature }}
  mysql.url: {{ .Values.mysql.url }}
  mysql.user: {{ .Values.mysql.user }}
  mysql.password: {{ .Values.mysql.password }}